### ISSUE TITLE
Autodelete posts too old

### ISSUE THREAD

**Issue by maxbalves** [maxbalves/PostBy#38]
- [x] Research Parse CloudJob
- [x] Is it possible?
- [x] If so, implement code

**Comment by raozhang-fb** [comment]
Deleting a post by the App without a user's consent may not be a good idea. 
A better way to handle this is 
- consider to hide it from other users' timeline/trending view.
- consider to give it a label in the database for further human review and decision

Dislike is different from reporting abuse/violation. It is a way to express other users' feeling, but it doesn't necessarily mean the content defies the law or offend others.

It is also different from auto-deleting outdated posts, because that is due to data retention/expiration and that is equal to everyone.
